name = "in-season-cup-bot"
main = "./src/server.js"
compatibility_date="2023-05-18"

# [secrets]
# DISCORD_TOKEN
# DISCORD_PUBLIC_KEY
# DISCORD_APPLICATION_ID
# AWS_ACCESS_KEY_ID
# AWS_SECRET_ACCESS_KEY

[observability.logs]
enabled = true

[[d1_databases]]
binding = "ASSIGN_DB" # available in your Worker on env.DB
database_name = "assignments"
database_id = "390ae039-dc5f-43c3-ae66-0dbb479caf9f"

[triggers]
crons = ["*/10 * * * *"]
