name = "in-season-cup-bot"
main = "./src/server.js"
compatibility_date="2023-05-18"

# [secrets]
# DISCORD_TOKEN
# DISCORD_PUBLIC_KEY
# DISCORD_APPLICATION_ID
# AWS_ACCESS_KEY_ID
# AWS_SECRET_ACCESS_KEY

[observability.logs]
enabled = true
